### ISSUE TITLE
Bells-going-white bug

### ISSUE THREAD

**Issue by AngelaKrone** [CGUC/skybunk-mobile#66]
Brandon: "Icon indicating list of feeds subsribed to (blue bell icon beside feed name) disappears (becomes default white) after making a post. Posts for respective feeds still appear in "My Subscriptions" feed, though. Once this occurs, you cannot undo your subscription selections --> they always appear in "My Subscriptions" and you cannot remove them. // UPDATE: After closing and opening the app, the problem seems to have resolved itself."

**Comment by picklechips** [comment]
I don't think this has ever been reproduced. Not a priority
